name: Multi-Shell Environment Exercise
on: [push]

jobs:
  multi-shell-job:
    runs-on: windows-latest
    steps:
      - name: Bash - System Information
        shell: bash
        run: uname -a
        
      - name: PowerShell - Computer Information
        shell: pwsh
        run: |
          Get-ComputerInfo
          # $PSVersionTable
          # Get-Host | Select-Object Version
        
      - name: Python - Version Information
        shell: python
        run: |
          import sys
          print(sys.version)
          
      - name: Node.js - Version Information
        shell: node {0}
        run: |
          console.log(process.version)