name: first-workflow
on: [push]

jobs:
  shell-cmd-job:
    runs-on: windows-latest
    defaults: # Job Level Defaults (여기 위치가 맞음)
      run:
        shell: pwsh
    steps:
      - name: 파이썬 실행
        shell: python
        run: |
          import sys
          print(sys.version)
          
      - name: 노드 실행
        shell: node
        run: |
          console.log(process.version);
